name: recreapp
description: Aplicación recreativa educativa para niños.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/lenguaje.png
    - assets/images/matematicas.png
    - assets/images/ciencias.png
    - assets/images/cocina.png
    - assets/images/pasatiempos.png
    - assets/images/sopa_letras.png
    - assets/images/cuentacuentos.png
    - assets/images/bingo_numeros.png
    - assets/images/sumas_fichas.png
    - assets/images/semillas.png
    - assets/images/laberinto_agua.png
    - assets/images/limonada.png
    - assets/images/batido.png
    - assets/images/origami.png
    - assets/images/pintura.png
    - assets/images/illustracion_bienvenida.png
    # NUEVAS imágenes para Manualidades
    - assets/images/macetero.png
    - assets/images/cuaderno_viaje.png
    # NUEVAS imágenes para Experimentos
    - assets/images/experimento_volcan.png
    - assets/images/flipbook.png
    # NUEVAS imágenes para Letras
    - assets/images/adivinanzas_chiloe.png
    - assets/images/rapanui_contar.png
    # NUEVAS imágenes para Numeros
    - assets/images/puzzle_numeros.png
    - assets/images/bowling_tubos.png
    # NUEVAS imágenes para Cocina
    - assets/images/panqueques.png
    - assets/images/queque_yogur.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
